name: CI

on:
  push:
    branches:
      - master

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Build API and UI
        run: |
          cd api 
          pip install poetry
          poetry export --format=requirements.txt --output=requirements.txt --without-hashes --without dev
          cd ..
          cd bil-ui
          yarn
          yarn build
          cd ..
          pwd
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: builder555
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Verify build context contents
        run: |
          pwd
          ls -l
          echo "bil-ui/ contents:"
          ls -l bil-ui/
          echo "api/ contents:"
          ls -l api/
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: builder555/bil:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
